language: ruby
rvm:
  - 2.5
  - 2.6.0-preview2

addons:
  apt:
    sources:
    - sourceline: 'ppa:r3-team/libr3-daily'
    packages:
    - libr3-dev

install:
  - bundle install --retry=3
  - rake compile